os:
  - osx

before_install:
 - brew install qt5
 - brew link qt5 --force

script:
 - cd CorgiDS
 - qmake CorgiDS.pro
 - make
 - macdeployqt CorgiDS.app
 - zip -r -X corgids-mac.zip CorgiDS.app
 - ls

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: corgids-mac.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
