os:
  - osx

before_install:
 - brew install qt5

script:
 - cd CorgiDS
 - qmake CorgiDS.pro
 - make
 - ls

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: CorgiDS.app
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
