install:
  - set QTDIR=C:\Qt\5.9.2\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - cd CorgiDS
  - qmake CorgiDS.pro
  - mingw32-make
  - del /S *.o
  - del /S *.cpp
  - del /S *.h
  - C:\Qt\5.9.2\mingw53_32\bin\windeployqt.exe %APPVEYOR_BUILD_FOLDER%\CorgiDS\release
  - xcopy C:\Qt\5.9.2\mingw53_32\bin\libwinpthread-1.dll %APPVEYOR_BUILD_FOLDER%\CorgiDS\release /d
  - xcopy C:\Qt\5.9.2\mingw53_32\bin\libgcc_s_dw2-1.dll %APPVEYOR_BUILD_FOLDER%\CorgiDS\release /d
  - xcopy C:\Qt\5.9.2\mingw53_32\bin\libstdc++-6.dll %APPVEYOR_BUILD_FOLDER%\CorgiDS\release /d
artifacts: 
  - path: CorgiDS\release
    name: corgids-win32
deploy:
    provider: GitHub
    auth_token:
      secure: 1shBeF0MANsWhNSxaiiw98elI21rU8leMhmoXYaRcBV+KPDsqeBX/wjzNKyYy1Ws
    artifact: corgids-win32
    draft: false
    prerelease: false